# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cliproxyapi-plus-aarch64-darwin = {
    pname = "cliproxyapi-plus-aarch64-darwin";
    version = "7.3.12-1";
    src = fetchurl {
      url = "https://github.com/kaitranntt/CLIProxyAPIPlus/releases/download/v7.3.12-1/CLIProxyAPIPlus_7.3.12-1_darwin_aarch64_no-plugin.tar.gz";
      sha256 = "sha256-sg6qxivS8/bI/3Ceb+RSu99qlZDIz8e38Og8Qr4mhqM=";
    };
  };
  cliproxyapi-plus-aarch64-linux = {
    pname = "cliproxyapi-plus-aarch64-linux";
    version = "7.3.12-1";
    src = fetchurl {
      url = "https://github.com/kaitranntt/CLIProxyAPIPlus/releases/download/v7.3.12-1/CLIProxyAPIPlus_7.3.12-1_linux_aarch64_no-plugin.tar.gz";
      sha256 = "sha256-L+uhdfEjGXU6uR8CxJW9hjgoOE5dqZIcnV7/L4ItNA0=";
    };
  };
  cliproxyapi-plus-x86_64-darwin = {
    pname = "cliproxyapi-plus-x86_64-darwin";
    version = "7.3.12-1";
    src = fetchurl {
      url = "https://github.com/kaitranntt/CLIProxyAPIPlus/releases/download/v7.3.12-1/CLIProxyAPIPlus_7.3.12-1_darwin_amd64_no-plugin.tar.gz";
      sha256 = "sha256-w5utGH7P/jHm+KnbSQQ+2dZXJfp7aWmbWoDJcthl1TI=";
    };
  };
  cliproxyapi-plus-x86_64-linux = {
    pname = "cliproxyapi-plus-x86_64-linux";
    version = "7.3.12-1";
    src = fetchurl {
      url = "https://github.com/kaitranntt/CLIProxyAPIPlus/releases/download/v7.3.12-1/CLIProxyAPIPlus_7.3.12-1_linux_amd64_no-plugin.tar.gz";
      sha256 = "sha256-92hmTC2OH6KugBxpZrkRWSfTjgbETzMhZsh9mjWJLzg=";
    };
  };
  gowa = {
    pname = "gowa";
    version = "v9.6.0";
    src = fetchFromGitHub {
      owner = "aldinokemal";
      repo = "go-whatsapp-web-multidevice";
      rev = "v9.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-FGrcg+FkdmTgJsNOrGTEGRxluKo2NqPjbdC9hTXeZUA=";
    };
  };
  jcode-aarch64-darwin = {
    pname = "jcode-aarch64-darwin";
    version = "v0.93.0";
    src = fetchurl {
      url = "https://github.com/1jehuang/jcode/releases/download/v0.93.0/jcode-macos-aarch64.tar.gz";
      sha256 = "sha256-FTUCTHOIqL1i4UKjE9wvZzqTUqNqaF0GGceexAvdI1Q=";
    };
  };
  jcode-aarch64-linux = {
    pname = "jcode-aarch64-linux";
    version = "v0.93.0";
    src = fetchurl {
      url = "https://github.com/1jehuang/jcode/releases/download/v0.93.0/jcode-linux-aarch64.tar.gz";
      sha256 = "sha256-WTrcRRY0iWp+NS1UVbKy5HjqIuIWXMKgaGWloUxUOIo=";
    };
  };
  jcode-x86_64-darwin = {
    pname = "jcode-x86_64-darwin";
    version = "v0.93.0";
    src = fetchurl {
      url = "https://github.com/1jehuang/jcode/releases/download/v0.93.0/jcode-macos-x86_64.tar.gz";
      sha256 = "sha256-Aaz46+UHnBjULBzX6JWLKSWCVL7IhfER/r/aru3+XM8=";
    };
  };
  jcode-x86_64-linux = {
    pname = "jcode-x86_64-linux";
    version = "v0.93.0";
    src = fetchurl {
      url = "https://github.com/1jehuang/jcode/releases/download/v0.93.0/jcode-linux-x86_64.tar.gz";
      sha256 = "sha256-6e0YP/BnvBf1MObt/d2X7/iP2Be8IoESMHM3fw91Z6Q=";
    };
  };
  lightpanda-aarch64-darwin = {
    pname = "lightpanda-aarch64-darwin";
    version = "629cd1b02ae4f9965e95e063bb7c765a6a53afa6";
    src = fetchurl {
      url = "https://github.com/lightpanda-io/browser/releases/download/nightly/lightpanda-aarch64-macos";
      sha256 = "sha256-DIcnFzZ33LBURvnS1xLlVSqnN2E7fJ/02tFZ5V121pc=";
    };
    date = "2026-10-09";
  };
  lightpanda-aarch64-linux = {
    pname = "lightpanda-aarch64-linux";
    version = "629cd1b02ae4f9965e95e063bb7c765a6a53afa6";
    src = fetchurl {
      url = "https://github.com/lightpanda-io/browser/releases/download/nightly/lightpanda-aarch64-linux";
      sha256 = "sha256-gxVtwI0Meh3o5t8pt5VXaRQDxawW1K1xfAo8l/+WuTU=";
    };
    date = "2026-10-09";
  };
  lightpanda-x86_64-darwin = {
    pname = "lightpanda-x86_64-darwin";
    version = "629cd1b02ae4f9965e95e063bb7c765a6a53afa6";
    src = fetchurl {
      url = "https://github.com/lightpanda-io/browser/releases/download/nightly/lightpanda-x86_64-macos";
      sha256 = "sha256-GBgemj+y9KTbxY/4tIyQ3+KPzeHLXMxRoDPvSJenrCw=";
    };
    date = "2026-10-09";
  };
  lightpanda-x86_64-linux = {
    pname = "lightpanda-x86_64-linux";
    version = "629cd1b02ae4f9965e95e063bb7c765a6a53afa6";
    src = fetchurl {
      url = "https://github.com/lightpanda-io/browser/releases/download/nightly/lightpanda-x86_64-linux";
      sha256 = "sha256-xexvs/+VXS6QZoKWKK2FURhC1JgaHQivLRaDiHxoUwk=";
    };
    date = "2026-10-09";
  };
  lumen-x86_64-darwin = {
    pname = "lumen-x86_64-darwin";
    version = "v2.32.0";
    src = fetchurl {
      url = "https://github.com/jnsahaj/lumen/releases/download/v2.32.0/lumen-x86_64-apple-darwin.tar.gz";
      sha256 = "sha256-JUAQoRj7IlVlWJxWQR1RsnUh/MWpuUpdz5ov5wbZLpY=";
    };
  };
  pi-agent-rust-aarch64-darwin = {
    pname = "pi-agent-rust-aarch64-darwin";
    version = "v0.7.1";
    src = fetchurl {
      url = "https://github.com/Dicklesworthstone/pi_agent_rust/releases/download/v0.7.1/pi-darwin-arm64.tar.xz";
      sha256 = "sha256-4NegGK+V/x/9FXK8MsDPSNvVJcsQW4s++YBiZjW/tYk=";
    };
  };
  pi-agent-rust-x86_64-linux = {
    pname = "pi-agent-rust-x86_64-linux";
    version = "v0.7.1";
    src = fetchurl {
      url = "https://github.com/Dicklesworthstone/pi_agent_rust/releases/download/v0.7.1/pi-linux-amd64.tar.xz";
      sha256 = "sha256-NXwjuv9dPv135HRHlZGxuOdSL9tp67eqBF5No1Oxiyc=";
    };
  };
  zai = {
    pname = "zai";
    version = "v0.1.8";
    src = fetchFromGitHub {
      owner = "dotcommander";
      repo = "zai";
      rev = "v0.1.8";
      fetchSubmodules = false;
      sha256 = "sha256-nruE/9tmeEuEO/x4NPyb9cUkDe3MapSuBePPTRosHrw=";
    };
  };
  zerobrew-zb-aarch64 = {
    pname = "zerobrew-zb-aarch64";
    version = "v0.4.0";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.4.0/zb-darwin-arm64";
      sha256 = "sha256-M828ABO6uCtUDH32GdjcFR/nLJQiXmVyMaF6xagf3KQ=";
    };
  };
  zerobrew-zb-x86_64 = {
    pname = "zerobrew-zb-x86_64";
    version = "v0.4.0";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.4.0/zb-darwin-x64";
      sha256 = "sha256-CDicChVQHPv5Rx4Uu/40sopURDwWnWjcQiaVQAn4wfs=";
    };
  };
  zerobrew-zbx-aarch64 = {
    pname = "zerobrew-zbx-aarch64";
    version = "v0.4.0";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.4.0/zbx-darwin-arm64";
      sha256 = "sha256-JMRRiDqKKdQUaIQ3ak6zbXxGaThdGsSicTIVjfn9gSM=";
    };
  };
  zerobrew-zbx-x86_64 = {
    pname = "zerobrew-zbx-x86_64";
    version = "v0.4.0";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.4.0/zbx-darwin-x64";
      sha256 = "sha256-GEGGHL9bwsNUmcEdosWfYTZCgeC2HNuFfDHk0FJRVQw=";
    };
  };
}
